name: First-Workflow
on: 
  - workflow_dispatch
  - push
# Activity
# on: 
#   pull_request:
#      types: [opened,closed]
#   workflow_dispatch
jobs:
  first-job:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest] #combinations.. include and exclude used for different combinations
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: "Print Greeting"
        run: echo "Hello World!"

      - name: "Multi Line Comments"
        run: |
          echo "First Line"
          echo "Second Line"
  second-job:
    needs: first-job # Makes the job run in sequential order
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v3

      - name: "Install the node version"
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        id: run-tests
        continue-on-error: true
        run: npm test

      - name: Build the code
        run: npm build

      - name: Publish the js file
        id: publish
        run: find dist/assets/*.js -type f execdir echo 'script-file={}' >> $GITHUB_OUTPUT

      - name: Upload the artifacts
        uses: actions/upload-artifact@v3
        if: steps.run-tests.outcome == "failure"
        with:
          name: dist-files
          path: |
            dist
            package.json
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: "Output the values"
        run: echo "${{ toJson(github) }}"
      
      - name: "Downloading build artifacts"
        uses: actions/download-artifacts@v3
        with:
          name: dist-files