name: First-Workflow
on: 
  - workflow_dispatch
  - push
# Activity
# on: 
#   pull_request:
#      types: [opened,closed]
#   workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Greeting"
        run: echo "Hello World!"

      - name: "Multi Line Comments"
        run: |
          echo "First Line"
          echo "Second Line"
  second-job:
    needs: first-job # Makes the job run in sequential order
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v3

      - name: "Install the node version"
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: "Output the values"
        run: echo "${{ toJson(github) }}"
      